
---
- name: Install NVIDIA Drivers and Verify GPU Access
  hosts: my_servers
  become: yes
  tasks:


    - name: Install ubuntu-drivers-common
      apt:
        name: ubuntu-drivers-common
        state: present

    - name: Detect recommended NVIDIA driver
      shell: "ubuntu-drivers devices | grep -oE 'nvidia-driver-[0-9]+' | head -n 1"
      register: nvidia_recommendation
      changed_when: false

    - name: Display recommended NVIDIA driver
      debug:
        msg: "Installing NVIDIA driver: {{ nvidia_recommendation.stdout }}"

    - name: Install recommended NVIDIA driver
      apt:
        name: "{{ nvidia_recommendation.stdout }}"
        state: present

    - name: Reboot the system to apply NVIDIA driver changes
      reboot:

    - name: Verify NVIDIA installation
      command: nvidia-smi
      register: nvidia_status
      changed_when: false

    - name: Display NVIDIA installation output
      debug:
        msg: "{{ nvidia_status.stdout }}"



- name: Fix MongoDB GPG Key Issue and Install Docker with NVIDIA Toolkit
  hosts: my_servers
  become: yes
  tasks:

    - name: Remove MongoDB repository
      file:
        path: "/etc/apt/sources.list.d/mongodb-org-7.0.list"
        state: absent

    - name: Remove old MongoDB GPG keys
      file:
        path: "/etc/apt/trusted.gpg.d/mongodb-server-6.0.asc"
        state: absent

    - name: Clean up APT
      shell: |
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
      changed_when: false

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Remove conflicting container packages
      apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - containerd.io
          - runc
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Fix broken dependencies
      shell: "sudo apt-get install -f -y"
      changed_when: false

    - name: Install Docker and NVIDIA Container Toolkit
      apt:
        name:
          - docker.io
          - nvidia-container-toolkit
        state: present
        update_cache: yes


    - name: Restart Docker to apply configuration
      systemd:
        name: docker
        state: restarted



    - name: Run GPU-enabled Docker container
      docker_container:
        name: gpu_container
        image: nvidia/cuda:12.1.1-base-ubuntu22.04
        runtime: nvidia
        env:
          NVIDIA_VISIBLE_DEVICES: all
          NVIDIA_DRIVER_CAPABILITIES: all
        command: ["nvidia-smi"]
      register: gpu_container_output

    - name: Display GPU container output
      debug:
        msg: "{{ gpu_container_output.container.Config.Cmd | default('No output captured') }}"
