- name: Install and Run Docker-Compose
  hosts: my_servers
  become: yes
  vars:
    dest_dir: "/home/sentinel/test-ansible"
  tasks:
    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        validate_certs: no

    - name: Build and start MongoDB containers
      command: docker-compose -f {{ dest_dir }}/docker-compose-mongo.yaml up --build -d
      become_user: sentinel
